### PR TITLE
Filter xcassets also with exclusion pattern

### PR DESCRIPTION
**Pull request by tonyxiao**
Would love to push this all the way upstream but it seems that there is already a pull request for this :) So Submitting to here instead.

### CODE REVIEW

**Comment by tonyxiao** [comment]
Ooops, I added another commit that's not really intended to be part of this pull request, how can i get rid of it from this PR?

**Comment by carlossless** [comment]
Good question, I did a bit of searching, and you could probably cherry pick your commit to a separate branch, rebase this branch to your previous commit and push -f it. Otherwise I can just pull your one commit to my branch myself.

**Comment by carlossless** [comment]
Also regarding the exclusion, I should probably add the same thing for fonts, what do you think?

**Comment by carlossless** [comment]
Merged the commit you intended for this pull request by hand, and closing this PR. Cheers! 🍻

**Pull request closed without merging**
